var analysisFields = {
    'BULK-GEOCHEMISTRY':['SiO2','Al2O3','Fe2O3','MgO','CaO','Na2O','K2O','TiO2','P2O5','MnO','Cr2O3','Ni','Sc','Ba','Be','Co','Cs','Ga','Hf','Nb','Rb','Sn','Sr','Ta','Th','U','V','W','Zr','Y','La','Ce','Pr','Nd','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu','Mo','Cu','Pb','Zn','As','Cd','Sb','Bi','Ag','Au','Hg','Tl','Se','B','F','Li','Cl','CO2_total','S_total','Cr','Ge','In','PF','Total'],
    'FLUID-INCLUSION-RAMAN':['Inclusion_type','aqueous_phase','TmCO2','ThCO2','Tmd','Tmice','Thom','Raman_Co2','Raman_CH4','Raman_N2','Raman_H2','Bulk_H2O','Bulk_CO2','Bulk_CH4','Bulk_N2','Bulk_NaCl','dv'],
    'FLUID-INCLUSION-LA-ICP-MS':['Na23','Li7','B11','Mg24','K39','Ca44','Mn55','Fe57','Cu63','Zn66','75As','Rb85','Sr88','Sb122','Cs133','Ba137','W182','Pb208','U238'],
    'FLUID-INCLUSION-MICROTHERMOMETRY':['Inclusion_type','Thom','SWIR_illite_muscovite','SWIR_kaolin_polymorphs','SWIR_sudoite_clinochlore','clay_occurence','type_of_quartz','type_of_occurence','solid','Te','tmice','thyd','tsnacl','salinity_NaCl_CaCl2','eq_NaCl','eq_CaCl2','Cl','Na','Li ','B ','Mg ','K ','Ca ','Mn ','Fe ','Cu ','Zn ','As ','Sr ','Sb ','Ba ','W ','Pb ','U ','O2_gaz','CO2_gaz','N2_gaz','CH4_gaz','H2_gaz','H2S_gaz','fluorescence','vapor_fraction','Tmcl','ThC02'],
    'GRAPHITE':['12C','13C','13C_12C -1','d13C_12C-1_PDB','d13C_12C_SL','error_graph','H_graph','t_graph','d13C_12C-1_cor_vs_PBD','No','comments','distance_mineralization'],
    'PETROPHYSICS':['Kv','density_moy_abs','poro_H2O','poro_He','Vp_short_axis','Vp_long_axis_ms','Absolute_solid_density','Apparent_density','Porosity','Permeability','Magnetic_susceptibility','Resistivity','Thermic_conductivity','GRAPHITE_prop_Imagery'],
    'UO2-GEOCHEMISTRY':['Mineral','Age_6_8','Age_7_5','Age_7_6','B_ppm','Ti_ppm','V_ppm','Cr_ppm','Mn_ppm','Co_ppm','Ni_ppm','Ga_ppm','As_ppm','Sr_ppm','Y_ppm','Zr_ppm','Nb_ppm','Mo_ppm','Sb_ppm','Ba_ppm','La_ppm','Ce_ppm','Pr_ppm','Nd_ppm','Sm_ppm','Eu_ppm','Gd_ppm','Tb_ppm','Dy_ppm','Ho_ppm','Er_ppm','Tm_ppm','Yb_ppm','Lu_ppm','W_ppm','Bi_ppm','Th_ppm','Si_wt','P_wt','Ca_wt','V_wt','Fe_wt','Y_wt','Pb_wt','Th_wt','U_wt','Zr_wt','O_wt','Ti_wt','Mn_wt','Total_wt','207Pb_235U','207Pb_235U_unc','206Pb_238U','206Pb_238U_unc','correl_err','Concordance_age','delta_O18','d18O_min','d18O_max','Ip_nA','Is206Pb','238U','206Pb_U','UO_U','204Pb_206Pb','207Pb_206Pb','208Pb_206Pb','ThO_U','208Pb_Th','206Pb_235U','238U_206Pb','Pb207_Pb206'],
    'XRD-CLAY':['C001','C002','C003','C004','C005','C003_C005-1','D_range','C003prime','C002plusC004_C003prime-1','Y_xrd','I001','I002','I003','I003_C003-1','I001_C002','Main_clay_assemblage'],
    'CLAY-CRISTALLOGRAPHY':['WhiteMica','Smectite','IlliticPhen','IlliticMusc','Musc','Paragonite','Phengite','FeChl','IntChl','MgChl','Dickite','KaolWX','Dravite','Carbonate','Calcite','Montmorillonite','Error_sTSAS','SNR_sTSAS','Unbound_Water_sTSAS']}